// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VoiceCommentsExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "VoiceCommentsExtension.8d5f40ed-e801-469d-a3c6-1964b0df796d";
        public const string Name = "Voice Comments Extension for Visual Studio 2022";
        public const string Description = @"An extension for Visual Studio 2022 that allows to record and listen voice comments on code editor.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Ayrat Khaydarov (d7chelovechek)";
        public const string Tags = "voice;comments;voice-comments;visual-studio";
    }
}
