// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VoiceCommentsExtension
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string VoiceCommentsExtensionPackageString = "579efc8e-9144-48c6-abb3-c004b28793f7";
        public static Guid VoiceCommentsExtensionPackage = new Guid(VoiceCommentsExtensionPackageString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int RecordVoiceCommentCommandId = 0x9999;
    }
}